DickinsonDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from DickinsonDjango import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Museum.urls'), name="Museum"),
    path('Museum/', include('Museum.urls'), name="Museum"),
    path('api/', include('api.urls'), name="api"),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# Import the path and include functions from django.urls module.
# These functions are used for URL routing.
from django.urls import path, include

# Import the routers module from rest_framework.
# This module is used to automatically create the URL conf.
from rest_framework import routers

# Import the views from the current directory.
# These views are used to handle the requests.
from . import views

# Import views from drf_spectacular.
# These views are used to generate the API documentation.
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

# Create a default router object.
# The DefaultRouter class is a feature-rich router for a set of views.
router = routers.DefaultRouter()

# Register the viewsets with the router.
# This will create routes for model related operations (list, create, retrieve, update, destroy)
router.register(r'users', views.UserViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'poems', views.PoemViewSet)
router.register(r'gallerypieces', views.GalleryPieceViewSet)
router.register(r'essays', views.EssayViewSet)

app_name = 'api'  # namespace for the app

# The include function is used to include the router's URLs.
# The path function is used to route the URL pattern to the viewset.
urlpatterns = [
    path('', include(router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),  # Returns a .yaml file
    # UI to consume the API through a browser
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='api:schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='api:schema'), name='redoc'),  # Documentation
]

members/urls.py
from django.urls import path
from . import views

app_name = "my_members"

urlpatterns = [
    path('', views.login_member, name="login"),
    path('login_user/', views.login_member, name="login"),
    path('logout_user/', views.logout_member, name="logout"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('register/', views.register_member, name="register"),
    path('my_profile/', views.my_profile, name="my_profile"),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name="members-profile-detail")

]

members/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.html import format_html
from django.utils.http import urlencode


def profile_image_path(instance, filename):
    # Get the file extension
    _, ext = os.path.splitext(filename)
    # Generate a unique filename based on the user's ID
    filename = f"user_{instance.user.id}_profpic{ext}"
    # File will be uploaded to MEDIA_ROOT/profile_images/user_<id>/user_<id>_profpic.<ext>
    return os.path.join("profile_images", f"user_{instance.user.id}", filename)


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to=profile_image_path, blank=True, default='/profile_images/seal_default.png')
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    avatar.short_description = "Avatar's url"

    # Generates an url with a timestamp as a query parameter so that the image never gets cached.
    # This prevents the undesired behaviour that browsers will store a local copy of the profile
    # picture, preventing the user from seeing their new picture if they were to update it.
    def avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            url = self.avatar.url
            time = timezone.localtime().isoformat()
            return url + "?" + urlencode({'t': time})
        return None

    def delete_old_avatar(self):
        # Delete the old avatar file if it exists and is not the default one
        if self.avatar and 'default.png' not in self.avatar.name:
            try:
                os.remove(self.avatar.path)
            except FileNotFoundError:
                pass

    # Method to display the avatar image in the admin interface
    def image_tag(self):
        if self.avatar:
            return format_html('<img src="{}" width="100" height="100" />', self.avatar.url)
        else:
            return 'No Image Found'
    image_tag.short_description = ''

    def save(self, *args, **kwargs):
        # Delete old avatar before saving new one if avatar field has changed
        if self.pk:  # Check if instance already exists
            orig = Profile.objects.get(pk=self.pk)
            if orig.avatar != self.avatar:
                orig.delete_old_avatar()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Clear or reset fields instead of deleting the profile object
        self.bio = ""
        self.avatar = '/profile_images/seal_default.png'
        self.location = ""
        self.birth_date = None
        self.save()

    def __str__(self):
        return f"{self.user.username}'s Profile"

members/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from datetime import datetime

from .models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already exists")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileForm(ModelForm):
    avatar = forms.ImageField(label='Profile Picture', required=False, widget=forms.FileInput(
        attrs={"id": "image_field"}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'location', 'birth_date']
        widgets = {
            "birth_date": forms.SelectDateWidget(years=range(datetime.now().year + 1, datetime.now().year - 110, -1)),
        }


class ProfileAdminForm(ModelForm):
    avatar = forms.ImageField(widget=forms.ClearableFileInput())

    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'location', 'birth_date']

members/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.views.generic import DetailView

from .models import Profile

from members.forms import ProfileForm, SignUpForm


@never_cache
def login_member(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('home')
        else:
            messages.error(request, "There was an error logging in. Please try again")
            return redirect("login")
    else:
        form = AuthenticationForm()
    return render(request, "registration/login.html", {"form": form})


@never_cache
@login_required()
def logout_member(request):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect("login")


@never_cache
def register_member(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("home")
    else:
        form = SignUpForm()
    return render(request, "members/register.html", {"form": form})


@never_cache
@login_required()
def my_profile(request):
    return render(request, "members/my_profile.html")


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'members/profile_detail.html'


@never_cache
@login_required()
def update_profile(request):
    try:
        # Attempt to get the profile for the current user
        profile = request.user.profile
        # If profile exists, set instance attribute of the form to the existing profile
        form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    except Profile.DoesNotExist:
        # If profile doesn't exist, initialize form without instance
        form = ProfileForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        if form.is_valid():
            # Save the form
            form.save()
            return redirect("home")

    return render(request, "members/update_profile.html", {"form": form})

templates/members/create_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <title>User Profile</title>
</head>
<body class="bg-dark text-light">
<div class="container">
    <div class="row justify-content-center mt-4">
        <div class="col-md-6">
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            {% if user.is_authenticated %}
                <form action="{% url 'create_profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="id_bio" class="form-label">Bio</label><br>
                        {{ form.bio }}
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_avatar" class="form-label">Avatar</label><br>
                        {{ form.avatar }}
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_location" class="form-label">Location</label><br>
                        {{ form.location }}
                    </div>
                    <div class="mb-3">
                        <label for="id_birth_date" class="form-label">Birth Date</label><br>
                        {{ form.birth_date }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            {% else %}
                <p>Castañas</p>
            {% endif %}
            <a href="{% url 'home' %}" class="btn btn-outline-light mt-4">Home</a>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/members/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{% static 'members/css/registration_style.css' %}"/>
    <title>Login</title>
</head>
<body class="container">
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-11">
        {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger
            {% endif %} alert-dismissible fade show"
                 role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="alert alert-primary" role="alert">
                        You are logged is as {{ user.username }}
                    </div>
                </div>
                <div class="row">
                    <button id="logout-btn" type="submit" class="col btn btn-primary">Logout</button>
                </div>
                <div class="row">
                    <a class="text-center mt-4" href="{% url 'home' %}">Home</a>
                </div>
            </form>
        {% else %}
            <h4 class="text-center mb-3"><b>Enter your username and password</b></h4>
            <hr class="accessory"/>
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group mb-3">
                    <label class="mb-2" for="id_username">Username</label><br/>
                    {{ form.username }}
                </fieldset>
                <fieldset class="form-group mb-3">
                    <label class="mb-2" for="id_password">Password</label><br/>
                    {{ form.password }}
                </fieldset>
                <div class="box shadow">
                    <div class="circle"></div>
                </div>
                <div class="box shadow">
                    <div class="circle"></div>
                </div>
                <div class="box shadow">
                    <div class="circle"></div>
                </div>
                <div class="mt-4 d-flex flex-column align-items-center">
                    <button type="submit" class="btn mb-3" role="button">LOG IN</button>
                    <p class="mt-3">
                        Don't have an account? <a href="{% url 'register' %}">Register</a><br/>or
                    </p>
                    <a href="{% url 'home' %}" class="mt-3">GO BACK TO HOME PAGE</a>
                </div>
            </form>
        {% endif %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/members/my_profile.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'members/css/profile_style.css' %}"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
{% endblock %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12 mb-4">
                <img id="profile_image" src="{{ user.profile.avatar_url }}" alt="profile picture" data-bs-toggle="modal"
                     data-bs-target="#imageModal">
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <h2 class="mb-5">{{ user.username }}</h2>
                <div class="bio">{{ user.profile.bio }}</div>
            </div>
        </div>
        <P class="mt-3">
            <span class="material-symbols-large material-symbols-outlined location">person_pin_circle</span> {{ user.profile.location }}
        </P>
        <P class="mt-3">
            <span class="material-symbols-large material-symbols-outlined material-symbols-celebration">celebration</span>{{ user.profile.birth_date }}
        </P>
        <p class="d-flex justify-content-end">
            Edit profile
            <a href="{% url 'my_members:update_profile' %}"><span
                    class="material-symbols-large material-symbols-outlined">edit</span></a>
        </p>
    </div>
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <img id="modal_image" src="{{ user.profile.avatar_url }}" alt="Avatar" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/members/profile_detail.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'members/css/profile_style.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% endblock %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12 mb-4">
                <img id="profile_image" src="{{ object.avatar_url }}" alt="profile picture" data-bs-toggle="modal"
                     data-bs-target="#imageModal">
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <h2 class="mb-5">{{ object.user.username }}</h2>
                <div class="bio">{{ object.bio }}</div>
            </div>
        </div>
        <P class="mt-3">
            <span class="material-symbols-large material-symbols-outlined location">person_pin_circle</span> {{ object.location }}
        </P>
        <P class="mt-3">
            <span class="material-symbols-large material-symbols-outlined material-symbols-celebration">celebration</span>{{ object.birth_date }}
        </P>
    </div>
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <img id="modal_image" src="{{ object.avatar_url }}" alt="Avatar" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/members/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'members/css/registration_style.css' %}"/>
    <title>Registration</title>
</head>
<body class="container">
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-11">
        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible fade show"
                 role="alert">
                <strong>{{ form.errors }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        <h5 class="text-center mb-3"><img src="{% static 'members/images/baby.svg' %}" alt="baby"/><b>A new Dickinsonian
            is born !</b></h5>
        <hr class="accessory"/>
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group mb-3">
                <label class="mb-2" for="username">Username</label><br/>
                {{ form.username }}
            </fieldset>
            <fieldset class="form-group mb-3">
                <label class="mb-2" for="email">Email address</label><br/>
                {{ form.email }}
            </fieldset>
            <fieldset class="form-group mb-3">
                <label class="mb-2" for="password1">Password</label><br/>
                {{ form.password1 }}
            </fieldset>
            <div class="form-check form-switch d-flex">
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" onclick="showPass()"/>
                <label id="showpass" class="form-check-label" for="flexSwitchCheckDefault">| Show Password</label>
            </div>
            <fieldset class="form-group mb-3">
                <label class="mb-2" for="password2">Repeat Password</label><br/>
                {{ form.password2 }}
            </fieldset>
            <div class="d-flex justify-content-center mt-3">
                <button type="submit" class="btn">Sign up</button>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'members/js/functions.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/members/update_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'members/css/registration_style.css' %}" />
    <title>Update Profile</title>
  </head>
  <body class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-11">
        {% for message in messages %}
          <div class="alert {% if message.tags == 'success' %}

            {% endif %} alert-dismissible fade show"
            role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
        {% if user.is_authenticated %}
          <h4 class="text-center mb-3"><img class="me-4" src="{% static 'members/images/meet.svg' %}" alt="baby" /><b>Pleased to meet you !</b></h4>
          <hr class="accessory" />
          <form action="{% url 'my_members:update_profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
              <div class="alert alert-danger" role="alert">
                <p>
                  <strong>Please, correct the errors below:</strong>
                </p>
                {{ form.errors }}
              </div>
            {% endif %}
            <div class="d-flex flex-column form-group mb-3">
              <label class="form-label">Avatar</label><br />
              <img id="profile_image" src="{{ user.profile.avatar_url }}" alt="profile picture" /><br />
              {{ form.avatar }}
            </div>
            <div class="form-group mb-3">
              <label for="id_bio" class="form-label">Bio</label><br />
              {{ form.bio }}
            </div>
            <div class="form-group mb-3">
              <label for="id_location" class="form-label">Location</label><br />
              {{ form.location }}
            </div>
            <div class="mb-3">
              <label for="id_birth_date" class="form-label">Birth Date</label><br />
              {{ form.birth_date }}
            </div>
            <div class="container p-0">
              <div class="row d-flex flex-row justify-content-between">
                <div class="col-6">
                  <button type="submit" class="btn">Update</button>
                </div>
                <div class="col-6 d-flex justify-content-end">
                  <a href="{% url 'my_members:my_profile' %}"><button type="button" class="btn btn-cancel">Discard</button></a>
                </div>
              </div>
            </div>
          </form>
        {% else %}
          <p>You are not logged in</p>
          <a href="{% url 'home' %}" class="btn btn-outline-light mt-4">Home</a>
        {% endif %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'members/js/functions.js' %}"></script>
  </body>
</html>

templates/members/user_profile.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <h1>Profile</h1>
    <p>Profile picture: <img id="profile_image" src="{{ user.profile.avatar.url }}" alt="profile picture"></p>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <P>Bio: {{ user.profile.bio }}</P>
    <P>Location: {{ user.profile.location }}</P>
    <P>Birth date: {{ user.profile.birth_date }}</P>
    <p>Update my profile <a href="{% url 'update_profile' %}">here</a></p>
{% endblock %}