DickinsonDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from DickinsonDjango import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Museum.urls'), name="Museum"),
    path('Museum/', include('Museum.urls'), name="Museum"),
    path('api/', include('api.urls'), name="api"),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Museum/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    # Class-based views for Poems
    path("poems/", views.PoemListView.as_view(), name="poems"),
    path("poems/<int:pk>/", views.PoemDetailView.as_view(), name="museum-poem-detail"),
    path("poems/new/", views.PoemCreateView.as_view(), name="museum-poem-create"),
    path('poems/<str:category>/', views.PoemCategoryListView.as_view(), name='poems_by_category'),
    path(
        "poems/<int:pk>/update/",
        views.PoemUpdateView.as_view(),
        name="museum-poem-update",
    ),
    path(
        "poems/<int:pk>/delete/",
        views.PoemDeleteView.as_view(),
        name="museum-poem-delete",
    ),
    # Class-based views for the gallery
    path("gallery/", views.GalleryPieceListView.as_view(), name="gallery"),
    path("gallery/<int:pk>/", views.GalleryPieceDetailView.as_view(), name="museum-gallerypiece-detail"),
    path(
        "gallery/new/",
        views.GalleryPieceCreateView.as_view(),
        name="museum-gallerypiece-create",
    ),
    path('gallery/<str:category>/', views.GalleryPieceCategoryListView.as_view(), name='gallerypieces_by_category'),
    path(
        "gallery/<int:pk>/update/",
        views.GalleryPieceUpdateView.as_view(),
        name="museum-gallerypiece-update",
    ),
    path(
        "gallery/<int:pk>/delete/",
        views.GalleryPieceDeleteView.as_view(),
        name="museum-gallerypiece-delete",
    ),
    # Class-based views for essays
    path("essays/", views.EssayListView.as_view(), name="essays"),
    path("essays/<int:pk>", views.EssayDetailView.as_view(), name="museum-essay-detail"),
    path("essays/<int:pk>/download", views.download_essay, name="museum-essay-download"),
    path("essays/new/", views.EssayCreateView.as_view(), name="museum-essay-create"),
    path('essays/<str:category>/', views.EssayCategoryListView.as_view(), name='essays_by_category'),
    path(
        "essays/<int:pk>/update/",
        views.EssayUpdateView.as_view(),
        name="museum-essay-update",
    ),
    path(
        "essays/<int:pk>/delete/",
        views.EssayDeleteView.as_view(),
        name="museum-essay-delete",
    ),
    path("contact/", views.contact, name="contact"),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls"), name="members"),
]

api/urls.py
# Import the path and include functions from django.urls module.
# These functions are used for URL routing.
from django.urls import path, include

# Import the routers module from rest_framework.
# This module is used to automatically create the URL conf.
from rest_framework import routers

# Import the views from the current directory.
# These views are used to handle the requests.
from . import views

# Import views from drf_spectacular.
# These views are used to generate the API documentation.
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

# Create a default router object.
# The DefaultRouter class is a feature-rich router for a set of views.
router = routers.DefaultRouter()

# Register the viewsets with the router.
# This will create routes for model related operations (list, create, retrieve, update, destroy)
router.register(r'users', views.UserViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'poems', views.PoemViewSet)
router.register(r'gallerypieces', views.GalleryPieceViewSet)
router.register(r'essays', views.EssayViewSet)

app_name = 'api'  # namespace for the app

# The include function is used to include the router's URLs.
# The path function is used to route the URL pattern to the viewset.
urlpatterns = [
    path('', include(router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),  # Returns a .yaml file
    # UI to consume the API through a browser
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='api:schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='api:schema'), name='redoc'),  # Documentation
]

members/urls.py
from django.urls import path
from . import views

app_name = "my_members"

urlpatterns = [
    path('', views.login_member, name="login"),
    path('login_user/', views.login_member, name="login"),
    path('logout_user/', views.logout_member, name="logout"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('register/', views.register_member, name="register"),
    path('my_profile/', views.my_profile, name="my_profile"),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name="members-profile-detail")

]

Museum/views.py
from django.http import FileResponse
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from Museum.models import Poem, GalleryPiece, Essay

from .forms import PoemCreateForm, PoemUpdateForm, GalleryPieceCreateForm, \
    GalleryPieceUpdateForm, EssayCreateForm, EssayUpdateForm

from django.db.models import Count


# Create your views here.
def home(request):
    return render(request, "Museum/home.html")


"""
Class-based view which renders the whole collection of poems present in the
database, ordered by update datetime.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.list.ListView

"""


class PoemListView(ListView):
    model = Poem
    template_name = "Museum/poems.html"
    context_object_name = "poems"
    ordering = ["-updated_at"]
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # the categories and the number of models which fall under that category
        context['categories'] = Poem.objects.values('category').annotate(count=Count('category'))
        return context


"""
Class-based view which renders a collection of poems present in the
database which fall under a given category.

    extends:
PoemListView

"""


class PoemCategoryListView(PoemListView):
    def get_queryset(self):
        return Poem.objects.filter(category=self.kwargs['category'])


"""
Class-based view which renders a specific poem present in the
database.

    extends:
django.views.generic.detail.DetailView

"""


class PoemDetailView(DetailView):
    model = Poem
    template_name = 'Museum/poem_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # three random poems
        context['random_poems'] = Poem.objects.order_by('?')[:5]
        return context


"""
Class-based view which renders a creation form for a poem.

    extends:
django.views.generic.edit.CreateView

"""


class PoemCreateView(LoginRequiredMixin, CreateView):
    model = Poem
    form_class = PoemCreateForm
    template_name = "Museum/poem_form.html"
    success_url = reverse_lazy("poems")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


"""
Class-based view which renders a form to update a specific poem.

    extends:
django.views.generic.edit.UpdateView

"""


class PoemUpdateView(LoginRequiredMixin, UpdateView):
    model = Poem
    form_class = PoemUpdateForm
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("poems")


"""
Class-based view which allows the deletion of a specific poem.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.edit.DeleteView

"""


class PoemDeleteView(LoginRequiredMixin, DeleteView):
    model = Poem
    template_name = "Museum/poem_confirm_delete.html"
    success_url = reverse_lazy("poems")


"""
Class-based view which renders the whole collection of gallery pieces present in the database, ordered
by update datetime.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.list.ListView

"""


class GalleryPieceListView(ListView):
    model = GalleryPiece
    template_name = "Museum/gallery.html"
    context_object_name = "gallery_pieces"
    ordering = ["-updated_at"]
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # the categories and the number of models which fall under that category
        context['categories'] = GalleryPiece.objects.values('category').annotate(count=Count('category'))
        return context


"""
Class-based view which renders a collection of gallery pieces present in the
database which fall under a given category.

    extends:
GalleryPieceListView

"""


class GalleryPieceCategoryListView(GalleryPieceListView):
    def get_queryset(self):
        return GalleryPiece.objects.filter(category=self.kwargs['category'])


"""
Class-based view which renders a specific gallery piece present in the
database.

    extends:
django.views.generic.detail.DetailView

"""


class GalleryPieceDetailView(DetailView):
    model = GalleryPiece
    template_name = 'Museum/gallerypiece_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # three random poems
        context['random_pieces'] = GalleryPiece.objects.order_by('?')[:5]
        return context


"""
Class-based view which renders a creation form for a gallery piece.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.edit.CreateView

"""


class GalleryPieceCreateView(LoginRequiredMixin, CreateView):
    model = GalleryPiece
    form_class = GalleryPieceCreateForm
    template_name = "Museum/gallery_piece_form.html"
    success_url = reverse_lazy("gallery")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


"""
Class-based view which renders a form to update a specific gallery piece.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.edit.UpdateView

"""


class GalleryPieceUpdateView(LoginRequiredMixin, UpdateView):
    model = GalleryPiece
    form_class = GalleryPieceUpdateForm
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("gallery")


"""
Class-based view which allows the deletion of a specific gallery piece.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.edit.DeleteView

"""


class GalleryPieceDeleteView(LoginRequiredMixin, DeleteView):
    model = GalleryPiece
    template_name = "Museum/gallery_piece_confirm_delete.html"
    success_url = reverse_lazy("gallery")


"""
Class-based view which renders the whole collection of essays present in the database, ordered
by update datetime.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.list.ListView

"""


class EssayListView(ListView):
    model = Essay
    template_name = "Museum/essays.html"
    context_object_name = "essays"
    ordering = ["-updated_at"]
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # the categories and the number of models which fall under that category
        context['categories'] = Essay.objects.values('category').annotate(count=Count('category'))
        return context


"""
Class-based view which renders a collection of essays present in the
database which fall under a given category.

    extends:
EssayListView

"""


class EssayCategoryListView(EssayListView):
    def get_queryset(self):
        return Essay.objects.filter(category=self.kwargs['category'])


"""
Class-based view which renders a detail view for an essay.

    extends:
django.views.generic.edit.DetailView

"""


class EssayDetailView(DetailView):
    model = Essay
    template_name = 'Museum/essay_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adds a new variable to the context consisting of a dictionary of dictionaries with
        # three random poems
        context['random_essays'] = Essay.objects.order_by('?')[:5]
        return context


"""
View which downloads an essay's pdf file.

"""


def download_essay(request, pk):
    essay = get_object_or_404(Essay, pk=pk)
    response = FileResponse(essay.file)
    filename = essay.title + ".pdf"
    response['Content-Disposition'] = 'attachment; filename="%s"' % filename
    return response


"""
Class-based view which renders a creation form for an essay.

    extends:
django.views.generic.edit.CreateView

"""


class EssayCreateView(LoginRequiredMixin, CreateView):
    model = Essay
    form_class = EssayCreateForm
    template_name = "Museum/essay_form.html"
    success_url = reverse_lazy("essays")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


"""
Class-based view which renders a form to update a specific essay.

    extends:
django.views.generic.edit.UpdateView

"""


class EssayUpdateView(LoginRequiredMixin, UpdateView):
    model = Essay
    form_class = EssayUpdateForm
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("essays")


"""
Class-based view which allows the deletion of a specific essay.

    extends:
django.contrib.auth.mixins.LoginRequiredMixin
django.views.generic.edit.DeleteView

"""


class EssayDeleteView(LoginRequiredMixin, DeleteView):
    model = Essay
    template_name = "Museum/essay_confirm_delete.html"
    success_url = reverse_lazy("essays")


def contact(request):
    return render(request, "Museum/contact.html")

templates/Museum/essay_confirm_delete.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'Museum/css/essays_style.css' %}"/>
{% endblock %}
{% block title %}
  Confirm essay deletion
{% endblock %}
{% block content %}
  <h1>This is the essay deletion confirmation page</h1>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm" />
  </form>
{% endblock %}

templates/Museum/essay_detail.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'Museum/css/essays_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'Museum/css/essay_detail_style.css' %}"/>
{% endblock %}
{% block title %}
    Essay Detail
{% endblock %}
{% block content %}
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="d-flex flex-row align-items-start">
                    <img class="pdf-cover me-3" src="data:image/png;base64,{{ essay.get_pdf_cover }}" alt="{{ object.title }}"/>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12">
                <a href="{% url 'museum-essay-download' object.id %}" download="{{ object.title }}">
                    <button type="button" class="btn btn-danger mb-5">Download PDF</button>
                </a>
                <h1>{{ object.title }}</h1>
                <p><strong>Author:</strong> {{ object.author }}</p>
                {{ object.abstract|safe }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <!-- Make sure only the user who uploaded the poem can edit it -->
                {% if user == object.user %}
                    <a class="mb-2" href="{% url 'museum-gallerypiece-update' object.id %}">
                        <i class="fa-solid fa-pen-nib"></i>
                        Edit
                    </a>
                    <a href="{% url 'museum-gallerypiece-delete' object.id %}">
                        <i class="fa-solid fa-trash-can"></i>
                        Delete
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{% endblock %}

templates/Museum/essay_form.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'Museum/css/essays_style.css' %}"/>
{% endblock %}
{% block title %}
    New Essay
{% endblock %}
{% block content %}
    <div class="container pt-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
{% endblock %}
{% block js %}

{% endblock %}

templates/Museum/essay_update_form.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'Museum/css/essays_style.css' %}"/>
{% endblock %}
{% block title %}
  Update Essay
{% endblock %}
{% block content %}
    {%  if user == object.user %}
        <div class="container pt-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% crispy form %}
            </form>
        </div>
    {% else %}
        <h1 class="text-center mt-5">You did not upload this!</h1>
    {% endif %}
{% endblock %}
{% block js %}

{% endblock %}

templates/Museum/gallery_piece_confirm_delete.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'Museum/css/gallery_style.css' %}" />
{% endblock %}
{% block title %}
  Confirm piece deletion
{% endblock %}
{% block content %}
    <h1>This is the gallery piece deletion confirmation page</h1>
    {%  if user == object.user %}
        <div class="container pt-4">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                {{ form }}
                <input type="submit" value="Confirm" />
            </form>
        </div>
    {% else %}
        <h1 class="text-center mt-5">You did not upload this!</h1>
    {% endif %}
{% endblock %}

templates/Museum/parent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'Museum/css/parent.css' %}"/>
    <link rel="stylesheet" href="{% static 'font-awesome/css/all.css' %}"/>
    {% block head %}
        <link type="image/png" sizes="32x32" rel="icon" href="{% static 'Museum/images/favicon_museum.png' %}"/>
    {% endblock %}
    <title>
        {% block title %}
            Base Template
        {% endblock %}
    </title>
</head>
<body>
<div class="container-fluid page-container">
    <nav class="shadow-lg navbar navbar-expand-lg navbar-dark justify-content-center">
        <div class="container-fluid">
            <a class="navbar-brand">
                <div class="d-flex">
                    <div class="d-flex flex-column align-items-center justify-content-center h-100">
                        <img id="emily-brand" src="{% static 'Museum/images/emily_dickinson.jpg' %}" alt="emily dickinson brand" />
                    </div>
                    <div class="col ms-2">
                        <hr class="hr-brand">
                        <div class="text-center align-items-start justify-content-start">
                            <p class="title-brand">THE</p>
                            <p id="dickinsonian-brand" class="title-brand">Dickinsonian</p>
                            <p class="title-brand">MUSEUM</p>
                        </div>
                        <hr class="hr-brand">
                    </div>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu">
                    <li class="nav-item {% if request.path == '/Museum/' %}{% endif %}">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item {% if 'poems' in request.path %}{% endif %}">
                        <a class="nav-link" href="{% url 'poems' %}">Poems</a>
                    </li>
                    <li class="nav-item {% if 'essays' in request.path %}{% endif %}">
                        <a class="nav-link" href="{% url 'essays' %}">Essays</a>
                    </li>
                    <li class="nav-item {% if 'gallery' in request.path %}{% endif %}">
                        <a class="nav-link" href="{% url 'gallery' %}">Gallery</a>
                    </li>
                    <li class="nav-item {% if 'contact' in request.path %}{% endif %}">
                        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0 custom-me">
                    {% if user.is_authenticated %}
                        <div class="profile-pic">
                            {% if 'default' not in user.profile.avatar.name %}
                                <img src="{% static 'Museum/images/seal_frame.png' %}" alt="Seal frame"/>
                            {% endif %}
                            <img src="{{ user.profile.avatar_url }}" alt="Profile picture"/>
                        </div>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false"><img id="dropdown-svg"
                                                                                    src="{% static 'members/images/profile-dropdown.svg' %}"
                                                                                    alt="dropdown-svg"/></a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'my_members:my_profile' %}">My Profile</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'museum-poem-create' %}">New Poem</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'museum-gallerypiece-create' %}">New Gallery Piece</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'museum-essay-create' %}">New Essay</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider"/>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'my_members:logout' %}">
                                        <img id="logout-svg" src="{% static 'members/images/logout.svg' %}"
                                             alt="logout-svg"/>
                                        Log Out
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'my_members:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% for message in messages %}
        <div class="alert {% if message.tags == 'success' %}
        {% endif %} alert-dismissible fade show"
             role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
</div>
<!-- Site footer -->
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify">I am a software developer based in Seville, Spain.</p>
                <p>This project would not have been possible without the help of my talented
                    friend Alejandro Tapia.</p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Good stuff</h6>
                <ul class="footer-links">
                    <li><a href="https://github.com/PabrodzamDEV/Dickinsonian-Museum"> Project's Repo</a></li>
                    <li><a href="https://open.spotify.com/intl-es/artist/6anw2OGFTMz6NMZ3wmH9tc"> Alejandro's Music</a>
                    </li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li><a href="{% url 'api:swagger-ui' %}">API</a></li>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'poems' %}">Poems</a></li>
                    <li><a href="{% url 'gallery' %}">Gallery</a></li>
                    <li><a href="{% url 'essays' %}">Essays</a></li>
                    <li><a href="{% url 'contact' %}">About Us/Contact</a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p>By the way, kudos to scanfcode for making this awesome footer! :)
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="email" href="mailto:pabrodzamdev@gmail.com"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                    <li><a class="github" href="https://github.com/PabrodzamDEV"><i class="fa-brands fa-github"></i></a></li>
                    <li><a class="linkedin" href="https://www.linkedin.com/in/pablo-rodríguez-zambrana-a820382b7/"><i class="fa-brands fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'Museum/js/parent.js' %}"></script>
{% block js %}

{% endblock %}
</body>
</html>

templates/Museum/poem_detail.html
{% extends 'Museum/parent.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'Museum/css/poems_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'Museum/css/poem_detail_style.css' %}"/>
{% endblock %}
{% block title %}
    Poem Detail
{% endblock %}
{% block content %}
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-12">
                <p id="poem-header" class="text-end me-5 text-break">{{ poem.title }}</p>
                <p id="poem-line"></p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-12 order-lg-1 order-md-1 order-2 pt-3 more-poems">
                <div class="d-flex flex-column align-items-center justify-content-center">
                    <div class="poem-list">
                        <h2 class="text-center mb-3">READ A RANDOM POEM</h2>
                        <div class="container text-center">
                            {% for poem in random_poems %}
                                <a href="{% url 'museum-poem-detail' poem.id %}">
                                    <h4>{{ poem.title }}</h4>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="envelope-container">
                    <img id="envelope" src="{% static 'Museum/images/envelope-closed.svg' %}" alt="envelope">
                </div>
            </div>
            <div class="col-lg-8 col-md-6 col-12 order-lg-2 order-md-2 order-1">
                <div class="container-fluid poem-container mb-5">
                    <div class="row">
                        <div>
                            <div class="uploader-profile-pic">
                                <a href="{% url 'my_members:members-profile-detail' object.user.profile.id %}">
                                    {% if 'default' not in object.user.profile.avatar.name %}
                                        <img src="{% static 'Museum/images/seal_frame.png' %}" alt="Seal frame"/>
                                    {% endif %}
                                    <img class="img-fluid" src="{{ object.user.profile.avatar_url }}" alt="Profile picture"/>
                                </a>
                            </div>
                        </div>
                        <div class="container-fluid d-flex flex-column pt-3">
                            <!-- Make sure only the user who uploaded the poem can edit it -->
                            {% if user == object.user %}
                                <a class="mb-2" href="{% url 'museum-poem-update' object.id %}">
                                    <i class="fa-solid fa-pen-nib"></i>
                                    Edit
                                </a>
                                <a href="{% url 'museum-poem-delete' object.id %}">
                                    <i class="fa-solid fa-trash-can"></i>
                                    Delete
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="pt-3 mb-3">
                        <h5 class="mb-4">
                            From: <b>{{ object.author }}</b>
                        </h5>
                        {{ object.content|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'Museum/js/poem_detail.js' %}"></script>
{% endblock %}